<?php

/**
 * This is the model base class for the table "subscription".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subscription".
 *
 * Columns in table "subscription" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $hash
 * @property string $email
 * @property string $platform
 * @property string $category
 * @property integer $rss
 * @property string $time_created
 * @property string $time_updated
 *
 */
abstract class BaseSubscription extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subscription';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subscription|Subscriptions', $n);
	}

	public static function representingColumn() {
		return 'hash';
	}

	public function rules() {
		return array(
			array('hash, email, time_created, time_updated', 'required'),
			array('rss', 'numerical', 'integerOnly'=>true),
			array('hash', 'length', 'max'=>100),
			array('email, platform, category', 'length', 'max'=>255),
			array('platform, category, rss', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, hash, email, platform, category, rss, time_created, time_updated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'hash' => Yii::t('app', 'Hash'),
			'email' => Yii::t('app', 'Email'),
			'platform' => Yii::t('app', 'Platform'),
			'category' => Yii::t('app', 'Category'),
			'rss' => Yii::t('app', 'Rss'),
			'time_created' => Yii::t('app', 'Time Created'),
			'time_updated' => Yii::t('app', 'Time Updated'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('hash', $this->hash, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('platform', $this->platform, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('rss', $this->rss);
		$criteria->compare('time_created', $this->time_created, true);
		$criteria->compare('time_updated', $this->time_updated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}