<?php

/**
 * This is the model base class for the table "feed_open_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeedOpenLog".
 *
 * Columns in table "feed_open_log" available as properties of the model,
 * followed by relations of table "feed_open_log" available as properties of the model.
 *
 * @property integer $id
 * @property integer $subscription_id
 * @property integer $project_id
 * @property string $time_open
 *
 * @property Project $project
 * @property Subscription $subscription
 */
abstract class BaseFeedOpenLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'feed_open_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeedOpenLog|FeedOpenLogs', $n);
	}

	public static function representingColumn() {
		return 'time_open';
	}

	public function rules() {
		return array(
			array('subscription_id, project_id', 'required'),
      array('time_open', 'default', 'value' => date('Y-m-d H:i:s'), 'setOnEmpty' => true, 'on' => 'insert'),
        
			array('subscription_id, project_id', 'numerical', 'integerOnly'=>true),
			array('id, subscription_id, project_id, time_open', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'project' => array(self::BELONGS_TO, 'Project', 'project_id'),
			'subscription' => array(self::BELONGS_TO, 'Subscription', 'subscription_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'subscription_id' => null,
			'project_id' => null,
			'time_open' => Yii::t('app', 'Time Open'),
			'project' => null,
			'subscription' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('subscription_id', $this->subscription_id);
		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('time_open', $this->time_open, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}