<?php

/**
 * This is the model base class for the table "outside_links".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OutsideLinks".
 *
 * Columns in table "outside_links" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $category
 * @property string $sub_category
 * @property string $title
 * @property string $link
 * @property integer $position
 * @property string $keywords
 * @property integer $active
 * @property string $time_created
 *
 */
abstract class BaseOutsideLinks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'outside_links';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OutsideLinks|OutsideLinks', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('category, sub_category, title, link', 'required'),
			array('position, active', 'numerical', 'integerOnly'=>true),
			array('category, sub_category', 'length', 'max'=>128),
			array('title, link', 'length', 'max'=>256),
			array('keywords', 'length', 'max'=>500),
			array('position, keywords, active', 'default', 'setOnEmpty' => true, 'value' => null),
            array('time_created', 'default', 'value' => date('Y-m-d H:i:s'), 'setOnEmpty' => true),
			array('id, category, sub_category, title, link, position, keywords, active, time_created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category' => Yii::t('app', 'Category'),
			'sub_category' => Yii::t('app', 'Sub Category'),
			'title' => Yii::t('app', 'Title'),
			'link' => Yii::t('app', 'Link'),
			'position' => Yii::t('app', 'Position'),
			'keywords' => Yii::t('app', 'Keywords'),
			'active' => Yii::t('app', 'Active'),
			'time_created' => Yii::t('app', 'Time Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('sub_category', $this->sub_category, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('time_created', $this->time_created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}