<?php

/**
 * This is the model base class for the table "platform".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Platform".
 *
 * Columns in table "platform" available as properties of the model,
 * followed by relations of table "platform" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 *
 * @property Project[] $projects
 */
abstract class BasePlatform extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'platform';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Platform|Platforms', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'projects' => array(self::HAS_MANY, 'Project', 'platform_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'projects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}