<?php

/**
 * This is the model base class for the table "category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "category" available as properties of the model,
 * followed by relations of table "category" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $platform_id
 *
 * @property Platform $platform
 * @property Project[] $projects
 * @property Project[] $projects1
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, platform_id', 'required'),
			array('platform_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('id, name, platform_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'platform' => array(self::BELONGS_TO, 'Platform', 'platform_id'),
			'projects' => array(self::HAS_MANY, 'Project', 'category_id'),
			'projects1' => array(self::HAS_MANY, 'Project', 'platform_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'platform_id' => null,
			'platform' => null,
			'projects' => null,
			'projects1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('platform_id', $this->platform_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}