<?php

/**
 * This is the model base class for the table "project_origcategory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProjectOrigcategory".
 *
 * Columns in table "project_origcategory" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $project_id
 * @property integer $orig_category_id
 *
 */
abstract class BaseProjectOrigcategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'project_origcategory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProjectOrigcategory|ProjectOrigcategories', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('project_id, orig_category_id', 'required'),
			array('project_id, orig_category_id', 'numerical', 'integerOnly'=>true),
			array('id, project_id, orig_category_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'project_id' => Yii::t('app', 'Project'),
			'orig_category_id' => Yii::t('app', 'Orig Category'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('orig_category_id', $this->orig_category_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}